Thread

diff --git a/.github/workflows/thorvg_one_all_check_thread_sanitizer.yml b/.github/workflows/thorvg_one_all_check_thread_sanitizer.yml
--- a/.github/workflows/thorvg_one_all_check_thread_sanitizer.yml
+++ b/.github/workflows/thorvg_one_all_check_thread_sanitizer.yml
@@ -1,4 +1,4 @@
-name: Thorvg Rsvg Sanitizer
+name: Thorvg all check thread sanitizer
 
 on:
   push:
@@ -10,7 +10,7 @@ env:
   CARGO_TERM_COLOR: always
 
 jobs:
-  test_sanitizer:
+  test:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
@@ -24,7 +24,7 @@ jobs:
         run: |
           git clone https://github.com/thorvg/thorvg.git
           cd thorvg
-          meson . build -Dtools=svg2png -Db_sanitize=address,undefined
+          meson . build -Dtools=svg2png -Db_sanitize=thread
           sudo ninja -C build install
           cd ..
 
@@ -35,8 +35,23 @@ jobs:
         run: |
           wget -q https://github.com/qarmin/SVG-regression-finder/releases/download/0.2.0/SVG5BigPack.zip
           unzip -q SVG5BigPack.zip
-          mv misc/ci_settings.toml settings.toml
+          mv misc/ci_settings_as_much.toml settings.toml
 
       - name: Run tests
         run: |
           timeout -v 14400 target/release/svg_tester || true
+
+      - name: Store Broken files
+        uses: actions/upload-artifact@v4
+        with:
+          name: brokenFiles
+          path: BrokenFILES
+          if-no-files-found: ignore
+
+      # Fail if broken files path exists
+      - name: Fail if broken files
+        run: |
+          if [ -d BrokenFILES ]; then
+              echo "Broken files found"
+              exit 1
+          fi
diff --git a/.github/workflows/thorvg_thorvg_differences.yml b/.github/workflows/thorvg_thorvg_differences.yml
--- a/.github/workflows/thorvg_thorvg_differences.yml
+++ b/.github/workflows/thorvg_thorvg_differences.yml
@@ -41,13 +41,6 @@ jobs:
         run: |
           timeout -v 14400 target/release/svg_tester || true
 
-      - name: Store Ignored Images
-        uses: actions/upload-artifact@v4
-        with:
-          name: ignored-images
-          path: IgnoredSVG
-          if-no-files-found: ignore
-
       - name: Store Broken Images
         uses: actions/upload-artifact@v4
         with:
@@ -55,9 +48,10 @@ jobs:
           path: BrokenSVG
           if-no-files-found: ignore
 
-      - name: Store Problematic Images
-        uses: actions/upload-artifact@v4
-        with:
-          name: problematic-images
-          path: ProblematicSVG
-          if-no-files-found: ignore
+      # Fail if broken files path exists
+      - name: Fail if broken files
+        run: |
+          if [ -d BrokenSVG ]; then
+              echo "Broken files found - thorvg is not reproducible"
+              exit 1
+          fi
